version: '3.7'

services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      - redis
  
  celery:
    build:
      context: .
    container_name: celery_app
    command: celery -A ee:celery worker --loglevel=INFO
    depends_on:
      - redis
    
  flower:
    build:
      context: .
    container_name: flower_app
    command: celery -A ee:celery flower
    depends_on:
      - redis
    ports:
      - 8888:5555